// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"fungo/live/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/CoverPicture/:room_id/:name",
				Handler: CoverPictureHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/LiveInfo/:room_id",
				Handler: LiveInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/LiveRoomList/:page",
				Handler: LiveRoomListReqHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/liveRoom/:room_id",
				Handler: LiveRoomHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/live"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/CreateLiveRoom",
				Handler: CreateLiveRoomHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/EditLiveRoom",
				Handler: EditLiveRoomReqHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/LiveRoomState",
				Handler: LiveRoomStateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/Startlive",
				Handler: StartLiveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/StopLive",
				Handler: StopLiveHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/live"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/BulletChatMessage/:room_id",
				Handler: BulletChatHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/live"),
		rest.WithSSE(),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/SendBulletChat",
				Handler: SendBulletChatHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/live"),
	)
}
