// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GameDetailReq struct {
	ID uint64 `path:"id"`
}

type GameDetailRsp struct {
	Info        GameInfo          `json:"info"`
	Pictures    []string          `json:"pictures"`
	Description string            `json:"description"`
	Links       map[string]string `json:"links"`
}

type GameFileReq struct {
	ID uint64 `path:"id"`
}

type GameInfo struct {
	ID               uint64 `json:"id"`
	Title            string `json:"title"`
	Cover            string `json:"cover"`
	Author           uint64 `json:"author"`
	UpdatedAt        string `json:"updated_at"`
	CanDownload      bool   `json:"can_download"`
	CanOnlinePlaying bool   `json:"can_online_playing"`
	PlayTime         int    `json:"play_time"`
}

type GameListReq struct {
	Page int `path:"page"`
}

type GemeListRsp struct {
	Games []GameInfo `json:"games"`
}

type OnlineGameReq struct {
	ID       uint64 `path:"id"`
	FileName string `path:"file_name"`
}

type PictureReq struct {
	ID       uint64 `path:"id"`
	FileName string `path:"file_name"`
}

type UploadGameReq struct {
	Title            string            `json:"title"`
	Cover            string            `json:"cover"`
	CanDownload      bool              `json:"can_download"`
	CanOnlinePlaying bool              `json:"can_online_playing"`
	Description      string            `json:"description"`
	Pictures         []string          `json:"pictures"`
	Links            map[string]string `json:"links"`
}
