// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type LoginRsp struct {
	Token string `json:"token"`
}

type RegisterReq struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type SelfInfoRsp struct {
	UserName string `json:"user_name"`
	UserID   uint64 `json:"user_id"`
}

type UserCoverReq struct {
	UserID uint64 `path:"user_id"`
}

type UserInfoReq struct {
	UID uint64 `path:"uid"`
}

type UserInfoRsp struct {
	UserName string `json:"user_name"`
	UserID   uint64 `json:"user_id"`
}
