// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ArticleDetailReq struct {
	ID uint64 `path:"id"`
}

type ArticleDetailRsp struct {
	ArticleInfo
	Pictures []string `json:"pictures"`
	Content  string   `json:"content"`
}

type ArticleInfo struct {
	ID         uint64 `json:"id"`
	Author     uint64 `json:"author"`
	Time       string `json:"time"`
	Title      string `json:"title"`
	Section    uint32 `json:"section"`
	Summary    string `json:"summary"`
	CommentNum int    `json:"comment_num"`
	LookNum    int    `json:"look_num"`
	LikeNum    int    `json:like_num`
	PictureUrl string `json:"url"`
}

type ArticleListReq struct {
	Section uint32 `path:"section"`
	Page    int    `path:"page"`
}

type ArticleListRsp struct {
	Articles []ArticleInfo `json:"articles"`
}

type CommentInfo struct {
	ID      uint64 `json:"id"`
	UID     uint64 `json:"uid"`
	Content string `json:"content"`
	Time    string `json:"time"`
}

type CommentsReq struct {
	ID uint64 `path:"id"`
}

type CommentsRsp struct {
}

type HotArticleListRsp struct {
	Articles []ArticleInfo `json:"articles"`
}

type LikeReq struct {
	ID uint64 `path:"id"`
}

type PictureReq struct {
	ID  uint64 `path:"id"`
	MD5 string `path:"md5"`
}

type SendCommentsReq struct {
	ID      uint64 `json:"id"`
	Content string `json:"content"`
}

type UserArticleListReq struct {
	UID  uint64 `path:"uid"`
	Page int    `path:"page"'`
}

type UserArticleListRsp struct {
	Articles []ArticleInfo `json:"articles"`
}
