// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"fungo/articles/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/articleDetail/:id",
				Handler: ArticleDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/articleList/:section/:page",
				Handler: ArticleListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/articlePictures/:id/:md5",
				Handler: GetPicturesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comments/:id",
				Handler: CommentsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/userArticleList/:uid/:page",
				Handler: UserArticleListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/article"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/createArticle",
				Handler: CreateArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/deleteArticle",
				Handler: DeleteArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/like",
				Handler: LikeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sendComments",
				Handler: SendCommentsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/article"),
	)
}
