// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AnimateItem struct {
	ID          uint64   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Year        string   `json:"year"`
	Tags        []string `json:"tags"`
	State       string   `json:"state"`
	Num         int      `json:"num"`
}

type SearchAnimateByAIReq struct {
	Description string `path:"description"`
}

type SearchAnimateByAIRsp struct {
	Items     []AnimateItem `json:"items"`
	Message   string        `json:"message"`
	MissItems []string      `json:"miss_items"`
}
