// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AnimateItem struct {
	ID          uint64   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Year        string   `json:"year"`
	Tags        []string `json:"tags"`
	State       string   `json:"state"`
	Num         int      `json:"num"`
}

type FavoriteReq struct {
	Id uint64 `path:"id"`
}

type FavoriteRsp struct {
	Favorite bool `json:"favorite"`
}

type GetAllAnimatesRsp struct {
	MaxPage int      `json:"max_page"`
	List    []uint64 `json:"list"`
}

type GetAllAnimtesReq struct {
	Page int `path:"page"`
}

type GetAnimateDetailReq struct {
	ID uint64 `path:"id"`
}

type GetAnimateDetailRsp struct {
	Item AnimateItem `json:"item"`
}

type GetAnimateMagnetReq struct {
	ID  uint64 `path:"id"`
	NID int    `path:"nid"`
}

type GetAnimateMagnetRsp struct {
	Link string `json:"link"`
}

type GetAnimateReq struct {
	ID   uint64 `path:"id"`
	NID  int    `path:"nid"`
	Name string `path:"name"`
}

type GetFavoritesReq struct {
	Page int `path:"page"`
}

type GetFavoritesRsp struct {
	List []uint64 `json:"list"`
}

type GetRecommendAnimateListRsp struct {
	AnimateItems []AnimateItem `json:"animate_items"`
}

type GetSubscribeAndFavoriteReq struct {
	ID uint64 `path:"id"`
}

type GetSubscribeAndFavoriteRsp struct {
	Subscribe bool `json:"subscribe"`
	Favorite  bool `json:"favorite"`
}

type GetSubscribeInfoRsp struct {
	Infos []SubInfo `json:"infos"`
}

type GetSubscribesRsp struct {
	List []uint64 `json:"list"`
}

type GetTodayUpdatedAnimateListRsp struct {
	AnimateItems []AnimateItem `json:"animate_items"`
}

type SubInfo struct {
	ID          uint64 `json:"id"`
	Name        string `json:"name"`
	Time        string `json:"time"`
	Version     int    `json:"version"`
	Description string `json:"description"`
}

type SubscribeReq struct {
	Id uint64 `path:"id"`
}

type SubscribeRsp struct {
	Subscribe bool `json:"subscribe"`
}
