// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"fungo/game/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/gameDetail/:id",
				Handler: GameDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/gameFile/:id",
				Handler: DownloadGameHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/gameList/:page",
				Handler: GameListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/gamePicture/:id/:file_name",
				Handler: GetPicturesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/online/:id/:file_name",
				Handler: OnlineGameHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/game"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/uploadGame",
				Handler: UploadGameHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/game"),
	)
}
