// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BulletChatMessageReq struct {
	RoomID uint64 `path:"room_id"`
}

type BulletChatMessageRsp struct {
	Content  string `json:"content"`
	UserName string `json:"user_name"`
}

type CoverPictureReq struct {
	RoomID uint64 `path:"room_id"`
	Name   string `path:"name"`
}

type LiveInfo struct {
	UserID           uint64 `json:"user_id"`
	UserName         string `json:"user_name"`
	RoomID           uint64 `json:"room_id"`
	Title            string `json:"title"`
	CurrentPeopleNum int    `json:"current_people_num"`
	Description      string `json:"description"`
	Cover            string `json:"cover"`
}

type LiveInfoReq struct {
	RoomID uint64 `path:"room_id"`
}

type LiveRoomListReq struct {
	Page int `path:"page"`
}

type LiveRoomListRsp struct {
	LiveInfos []LiveInfo `json:"live_infos"`
}

type LiveRoomReq struct {
	RoomID uint64 `path:"room_id"`
}

type LiveRoomRsp struct {
	LiveInfo
	Key string `json:"key"`
}

type LiveRoomStateRsp struct {
	State  int    `json:"state"` // 1代表未创建直播间，2代表未开播，3代表已开播
	IP     string `json:"ip"`
	Key    string `json:"key"`
	RoomID uint64 `json:"room_id"`
}

type SendBulletChat struct {
	Content string `json:"content"`
	RoomID  uint64 `json:"room_id"`
}

type UserLiveRoomReq struct {
	UID uint64 `path:"uid"`
}

type UserLiveRoomRsp struct {
	State uint8 `json:"state"` // 0:未创建直播间，1：未开播，2：已开播
	LiveInfo
}
