// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"fungo/ai/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/searchAnimateByAI/:description",
				Handler: searchAnimateByAIHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/ai"),
	)
}
