// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"fungo/animate/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/favorite/:id",
				Handler: favoriteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getAllAnimates/:page",
				Handler: getAllAnimatesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getAnimate/:id/:nid/:name",
				Handler: getAnimateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getAnimateDetail/:id",
				Handler: getAnimateDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getFavorites/:page",
				Handler: getFavoritesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getRecommendAnimateList",
				Handler: recommendAnimateListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getSubscribeInfo",
				Handler: getSubscribeInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getSubscribes",
				Handler: getSubscribesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getTodayUpdatedAnimateList",
				Handler: todayUpdatedAnimateListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/querySubscribeAndFavorite/:id",
				Handler: querySubscribeAndFavoriteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/subscribe/:id",
				Handler: subscribeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/uploadAnimate",
				Handler: uploadAnimateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/animate"),
	)
}
