// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ArticleDetailReq struct {
	ID uint64 `path:"id"`
}

type ArticleDetailRsp struct {
	ArticleInfo
	Pictures []string `json:"pictures"`
	Content  string   `json:"content"`
}

type ArticleInfo struct {
	ID         uint64 `json:"id"`
	Author     uint64 `json:"author"`
	Time       string `json:"time"`
	Title      string `json:"title"`
	Section    uint32 `json:"section"`
	Summary    string `json:"summary"`
	CommentNum int    `json:"comment_num"`
	LookNum    int    `json:"look_num"`
	LikeNum    int    `json:"like_num"`
	PictureUrl string `json:"url"`
	IfLike     bool   `json:"if_like"`
}

type ArticleListReq struct {
	Section uint32 `path:"section"`
	Page    int    `path:"page"`
}

type ArticleListRsp struct {
	Articles []ArticleInfo `json:"articles"`
}

type CommentInfo struct {
	ID        uint64 `json:"id"`
	UID       uint64 `json:"uid"`
	CreatedAt string `json:"created_at"`
	Content   string `json:"content"`
	Parent    uint64 `json:"parent"`
	PParent   uint64 `json:"p_parent"`
}

type CommentsReq struct {
	ID uint64 `path:"id"`
}

type CommentsRsp struct {
	Comments []CommentInfo `json:"comments"`
}

type HotArticleListRsp struct {
	Articles []ArticleInfo `json:"articles"`
}

type LikeReq struct {
	ID uint64 `json:"id"`
}

type PictureReq struct {
	ID  uint64 `path:"id"`
	MD5 string `path:"md5"`
}

type SendCommentsReq struct {
	ArticleID uint64 `json:"article_id"`
	Content   string `json:"content"`
	Parent    uint64 `json:"parent"`
	PParent   uint64 `json:"p_parent"`
}

type UserArticleListReq struct {
	UID  uint64 `path:"uid"`
	Page int    `path:"page"`
}

type UserArticleListRsp struct {
	Articles []ArticleInfo `json:"articles"`
}
